# -*- coding: utf-8 -*-
"""lagrangian_cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3sRNEPWHJtfe_NX_FHCrf0ZCB7e-cX-
"""

import argparse
from lagrangian_hamiltonian_solver.core import build_locals, get_KE, get_PE, lagrangian, hamiltonian, lagrangian_equation

def main() -> None:
  parser = argparse.ArgumentParser(
        description="To derive and calculate conjugate moments, lagrangian, hamiltonian, lagrangian equation and find solution"
    )

  parser.add_argument(
        "co_ordinate",
        type=str,
        help="provide the generalised co-ordinates",
    )
  parser.add_argument(
        "constants",
        type=str,
        help="symbols used for constants",
    )


  

  subparsers =parser.add_subparsers(
        dest= "input_type",
        
        required=True,
        help="The nature of the input",
    )

  energies_parser = subparsers.add_parser(
        "energies",
        help="Use kinetic and potential energy as input",
    )

  energies_parser.add_argument(
        "KE",
        type=str,
        help="Kinetic energy expression",
    )
  
  energies_parser.add_argument(
        "PE",
        type=str,
        help="Potential energy expression",
    )

  lagrangian_parser = subparsers.add_parser(
        "lagrangian",
        help="Use Lagrangian as input",
    )

  lagrangian_parser.add_argument(
        "L",
        type=str,
        help="Lagrangian expression",
    )
  args = parser.parse_args()

  co_ordinate, constants, locals_map = build_locals(args.co_ordinate, args.constants)

  if args.input_type == "energies":
   
    KE = get_KE(args.KE,locals_map)
    PE = get_PE(args.PE,locals_map)
    L = lagrangian(KE,PE)
    H= hamiltonian(L, co_ordinate)
    eq= lagrangian_equation(L, co_ordinate,locals_map)
    print(L)
    print(H)
    print(eq)


  elif args.input_type == "lagrangian":
    
    
    H = hamiltonian(args.L, co_ordinate, locals_map)
    eq = lagrangian_equation(args.L,co_ordinate,locals_map)
    print(H)
    print(eq)

if __name__ == "__main__":
    main()