# -*- coding: utf-8 -*-
"""langrangian_core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sx_sRApbCGa8ZT0LtmxwfesRRBZsLKLO
"""

#headers
import sympy as sp
from sympy.parsing.sympy_parser import parse_expr
import numpy as np

t = sp.symbols("t")
q_i = sp.Function('q')(t)  # q(t)

# Building locals once: map q -> q(t), q_dot -> dq/dt
def build_locals(co_ordinate, constants):

  #parsing coordinates
  co_ordinate = [
        item.strip()
        for item in co_ordinate.split(",")
        if item.strip()
  ]
  co_ordinate = [sp.Function(item)(t) for item in co_ordinate]

  #parsing constants
  constants = [
        item.strip()
        for item in constants.split(",")
        if item.strip()
  ]
  constants = [sp.sympify(item) for item in constants]

  #creating loca map for coordinates
  locals_map = {'t': t}
  for q_i in co_ordinate:
        # q should be an AppliedUndef like x(t)
        base = q_i.func.__name__      # "x" from x(t)
        locals_map[base] = q_i
        locals_map[f'{base}_dot'] = sp.diff(q_i, t)
        locals_map[f'{base}_ddot'] = sp.diff(q_i, t, 2)
        locals_map[f'{base}_dddot'] = sp.diff(q_i, t, 3)
        locals_map[f'{base}_ddddot'] = sp.diff(q_i, t, 4)
  return co_ordinate, constants, locals_map

#kinetic energy
def get_KE(KE, locals_map):
  KE = sp.sympify(KE, locals_map)
  return KE

#potential energy
def get_PE(PE):
  PE = sp.sympify(PE)
  return PE

#lagrangian using potential and kinetic energies
def lagrangian(KE, PE):
  L= KE-PE
  return L

'''getting the lagrangian equation, solution and hamiltonian'''

def lagrangian_equation(L, co_ordinate, locals_map):
  L = sp.sympify(L, locals= locals_map)
  for q_i in co_ordinate:# for each generalised co-ordinate

    q_i_dot=sp.diff(q_i,t)

    p_i = sp.diff(L,q_i_dot)#conjugate momentum
    #print(f"conjugate momentum: {p_i}")

    equation = sp.diff(p_i,t)  -  sp.diff(L,q_i)
    #print(f"Lagrangian equation :{equation}=0")
    sol= sp.dsolve(sp.Eq((equation),0), q_i)
    #print(f"the solution: {sol}")
  return p_i, equation, sol

#getting the hamiltonian from lagrangian in generalized coordinates(not in phase space)
def hamiltonian(L, co_ordinate, locals_map):
  L = sp.sympify(L,locals = locals_map)
  q_dot_p = 0
  for q_i in co_ordinate:
    q_i_dot=sp.diff(q_i,t)
    p_i = sp.diff(L,q_i_dot)
    q_dot_p += q_i_dot * p_i# getting the q_i_dot * p_i term summation over i
  H = sp.Function('H')(t)# initializing Hamiltonian
  H= q_dot_p - L #expression for hamiltonian from lagrangian
  #print(f"Hamiltonian (H) in terms of co- ordinates = {H}")
  return H